#
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.
#
---

- set_fact:
    routes:
        - 172.20.90.0/24 via 192.168.33.40
        - 172.20.91.0/24 via 192.168.33.40
        - 172.20.90.0/24 via 192.168.33.40
        - 192.168.116.0/24 via 192.168.33.40
        - 192.168.117.0/24 via 192.168.33.40
        - 192.168.102.0/24 via 192.168.33.40
        - 192.168.108.0/24 via 192.168.33.40
        - 192.168.107.0/24 via 192.168.33.40
        - 192.168.112.0/22 via 192.168.33.40
        - 192.168.120.0/22 via 192.168.33.40

- lineinfile:
    dest: /etc/sysconfig/network-scripts/route-eth0
    create: yes
    line: "{{ item }}"
  with_items: "{{ routes }}"

- command: ip route replace {{ item }}
  with_items: "{{ routes }}"
