#
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.
#
---
- name: Add npm repos
  shell: >
    curl --silent -o /etc/yum.repos.d/yarn.repo https://dl.yarnpkg.com/rpm/yarn.repo;
    curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -

- name: Install additional rpm build packages
  yum: name={{ item }} state=latest
  with_items:
    - rpm-build
    - nodejs-6.4.0
    - yarn
    - gcc

- name: Building KuberDock RPM from source
  command: bash "{{ master_kd_src_path }}/dev-utils/build-rpm.sh" "{{ master_kd_src_path }}" "{{ master_rpms_dir }}"
  environment:
    KD_GIT_REF: "{{ git_ref | default('') }}"
    JS_BUILD_MODE: dev

- name: Building KCLI RPM from source
  command: bash "{{ master_kd_src_path }}/dev-utils/build-kdcli-rpm.sh" "{{ master_kd_src_path }}/kuberdock-cli" "{{ master_rpms_dir }}"
  environment:
    KDCLI_GIT_REF: "{{ git_ref | default('') }}"

- name: Building KDCTL RPM from source
  command: bash "{{ master_kd_src_path }}/dev-utils/build-kdctl-rpm.sh" "{{ master_kd_src_path }}/kuberdock-manage" "{{ master_rpms_dir }}"
  environment:
    KDCLI_GIT_REF: "{{ git_ref | default('') }}"
