---

- name: Copy CEPH config
  copy: src="{{ ceph_config }}" dest="{{ ceph_config_dest }}"
  when: ceph_config != ""
  tags:
      - ceph

- name: Copy CEPH keyring
  copy: src="{{ ceph_user_keyring }}" dest="{{ ceph_user_keyring_dest }}"
  when: ceph_user_keyring != ""
  tags:
      - ceph
        
- set_fact:
    ceph_params: "{{ pd_namespace_param }} --ceph-user \"{{ ceph_user }}\" --ceph-config \"{{ ceph_config_dest }}\" --ceph-user-keyring \"{{ ceph_user_keyring_dest }}\""

