---

- name: Disable stuff
  service: name=emperor.uwsgi state=stopped

- name: Proxy pass for nginx
  replace: 
    dest: /etc/nginx/conf.d/kuberdock-ssl.conf
    regexp: "include uwsgi_params;\n[ ]*uwsgi_pass 127.0.0.1:8009;" 
    replace: "proxy_pass http://127.0.0.1:5000;"
    backup: yes
  notify:
    - restart nginx

- name: Create tmux session
  shell: tmux has-session -t '{{ tmux_session_name }}'  || tmux new-session -d -s '{{ tmux_session_name }}' 
  tags:
      - tmux

- name: Up wsgi
  command: tmux new-window -t '{{ tmux_session_name }}' \; send-keys "sudo python wsgi.py" C-m chdir=/vagrant
  when: not no_wsgi
  tags:
      - tmux

- name: Up celery
  command: tmux new-window -t '{{ tmux_session_name }}' \; send-keys "{{ item }}" C-m chdir=/vagrant
  with_items:
    - "sudo -u nginx /usr/bin/celery -A kubedock.tasks --autoscale=16,4 worker -Ofair"
    - "sudo /usr/bin/celery -A kubedock.tasks beat -s /tmp/celerybeat-schedule"
  tags:
      - tmux

- name: Prepare test env
  command: bash /vagrant/dev-utils/prepare_test_env.sh

