- name: Install additional dev packages
  yum: name={{ item }} state=latest
  with_items:
      - rpm-build
      - nodejs
      - nodejs-less
      - nodejs-clean-css
      - gcc

- name: Building Kuberdock RPM from source
  command: bash /vagrant/dev-utils/build-rpm.sh
  environment:
    KD_GIT_REF: "{{ git_ref | default('') }}"

- name: Building KCLI RPM from source
  command: bash /vagrant/dev-utils/build-kdcli-rpm.sh
  environment:
    KDCLI_GIT_REF: "{{ git_ref | default('') }}"

- name: Building KDCTL RPM from source
  command: bash /vagrant/dev-utils/build-kdctl-rpm.sh
  environment:
    KDCTL_GIT_REF: "{{ git_ref | default('') }}"

- name: Notice not to unpack deploy.sh
  set_fact:
      deploy_extracted: true

- name: Override src path
  set_fact:
      src_prefix: /vagrant
