- stat: path="{{ master_rpms_dir }}/kdctl.rpm"
  register: kdctl_rpm

- fail: msg="kdctl.rpm was not found"
  when: not kdctl_rpm.stat.exists
  tags:
   - kdctl

- name: Install kdctl
  yum: name="{{ master_rpms_dir }}/kdctl.rpm" state=present
  tags:
   - kdctl

- name: Login by kdctl
  command: kdctl login --username admin --password admin
  tags:
   - kdctl
