---

- name: Get predefined apps
  git: repo="{{ predefined_apps_repo }}"
       dest="{{ predefined_apps_dest }}"
  tags:
  - predefined_apps

- name: Find all apps
  find: paths="{{ predefined_apps_dest }}" patterns=*.yaml
  register: predefined_apps
  tags:
  - predefined_apps

- name: Add predefined apps
  shell: for i in {{ predefined_apps_dest }}/*.yaml; do name=$(basename "$i"); python "{{ master_kd_src_path }}"/manage.py add-predefined-app --name "$name" -t "$i"; done
  async: 3600
  poll: 0
  register: pa_async_results
  tags:
  - predefined_apps
