---

- name: Adding routes for CEPH
  shell: ip route replace 192.168.101.0/24 via 192.168.33.40
  when: is_nebula and use_ceph
  tags:
    - route

- name: Adding persistent routes for CEPH
  lineinfile:
      dest: "/etc/sysconfig/network-scripts/route-{{ ansible_default_ipv4.interface }}"
      line: "192.168.101.0/24 via 192.168.33.40"
      create: yes
      state: present
  when: is_nebula and use_ceph
  tags:
    - route
